# Generated by Django 3.1 on 2020-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_Name', models.CharField(max_length=200)),
                ('Med_Dur', models.CharField(max_length=200)),
            ],
        ),
    ]
