# Generated by Django 3.1 on 2020-08-21 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_meddata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meddata',
            name='Mrg_med',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
